language: java
jdk:
  - openjdk11
before_script:
- psql -c 'create database travis_ci_test;' -U postgres
script:
  - mvn clean install
services:
  - postgresql
env:
global:
  - PGPORT=5432
  - DB_NAME=postgres
  - DB_USER=postgres
  - DB_PASSWORD=123456789
